TRIPLE=aarch64-linux-gnu
ARCH=AArch64
CPU=cortex-a57
SYSROOT=/srv/chroot/trusty-arm64
GCC=$TRIPLE-gcc-4.8
GCC_INC=/usr/$TRIPLE/include
GCC_V3=4.8.2
GCC_LIB=/usr/lib/gcc-cross/$TRIPLE/4.8/

GCC_CXX_FLAGS="-I$GCC_INC/c++/$GCC_V3/$TRIPLE/ -I$GCC_INC/c++/$GCC_V3/"
GCC_C_FLAGS="-I$GCC_INC/"
TARGET_C_FLAGS="-target $TRIPLE -mcpu=$CPU -I$SYSROOT/usr/include -I$SYSROOT/usr/include/$TRIPLE/ $FLOAT_ABI -ccc-gcc-name $GCC $GCC_C_FLAGS"
TARGET_CXX_FLAGS="$TARGET_C_FLAGS $GCC_CXX_FLAGS"

mkdir -p ./build/$TRIPLE/
cd ./build/$TRIPLE/ && rm -rf * && cmake -G Ninja ../../llvm \
-DCMAKE_C_COMPILER=$PWD/../host/bin/clang \
-DCMAKE_CXX_COMPILER=$PWD/../host/bin/clang++ \
-DCMAKE_CROSSCOMPILING=True \
-DCMAKE_INSTALL_PREFIX:PATH=$PWD/install \
-DLLVM_TABLEGEN=$PWD/../host/bin/llvm-tblgen \
-DCLANG_TABLEGEN=$PWD/../host/bin/clang-tblgen \
-DLLVM_DEFAULT_TARGET_TRIPLE=$TRIPLE \
-DLLVM_TARGET_ARCH=$ARCH \
-DLLVM_TARGETS_TO_BUILD=$ARCH \
-DCMAKE_C_FLAGS="$TARGET_C_FLAGS" \
-DCMAKE_CXX_FLAGS="$TARGET_CXX_FLAGS" \
-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
-DCMAKE_FIND_ROOT_PATH=$SYSROOT/ \
-DCMAKE_LIBRARY_PATH=$SYSROOT/usr/ \
-DCMAKE_LIBRARY_ARCHITECTURE=$TRIPLE \
-DCMAKE_EXE_LINKER_FLAGS="-L$GCC_LIB  -L$SYSROOT/usr/lib/  -L$SYSROOT/lib/  -L$SYSROOT/lib/$TRIPLE -L$SYSROOT/usr/lib/$TRIPLE/" \
-DCMAKE_BUILD_TYPE=Debug \
-DLLVM_BUILD_STATIC=True && \
ninja lldb-server
