rm -rf ./build/host
mkdir -p ./build/host
cd ./build/host
BUILD_TYPE=$1
C_COMPILER=clang
CXX_COMPILER=clang++
cmake -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
-DCMAKE_C_FLAGS="$CFLAGS" -DCMAKE_CXX_FLAGS="$CFLAGS" \
-DLLVM_ENABLE_EH=YES -DLLVM_ENABLE_RTTI=YES -DLLVM_ENABLE_ASSERTIONS=ON \
"-DLLVM_TARGETS_TO_BUILD=X86;ARM;AArch64" \
../../llvm
ninja -v


