cmake -G Ninja ^
-DCMAKE_BUILD_TYPE=Release ^
-DLLVM_ENABLE_ASSERTIONS=True ^
-DLLVM_LIT_ARGS='-v' ^
-DCMAKE_INSTALL_PREFIX=..\stage1.install ^
-DCMAKE_TRY_COMPILE_CONFIGURATION=Release ^
-DCMAKE_C_COMPILER_LAUNCHER=ccache ^
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache ^
-DCOMPILER_RT_BUILD_SANITIZERS=OFF ^
-DCOMPILER_RT_BUILD_PROFILE=OFF ^
-DLLVM_ENABLE_PROJECTS=lld;clang;llvm;mlir;flang;clang-tools-extra ^
-DLLVM_ENABLE_RUNTIMES=compiler-rt ^
../llvm-project/llvm
